baseURL = "http://example.org/eriqmapjapan"
title = "EriQmapJapan's Newsletter"
theme = "exampleTheme"
languageCode = "ja"
hasCJKLanguage = true
staticDir = ["static", "images", "img"]
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
 [[menu.main]]
    name = "Categories"
    pre = "categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

 [[menu.main]]
    name = "about"
    pre = "about"
    url = "/about/"
    weight = 3

[taxonomies]
	tag = "tags"
	category = "categories"
	archive = "archives"

paginate = 1

[Params.social.share]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = true
  email = true

